spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC
      username: root
      password: 112713@asD
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.example.entity
